#pragma once

#define IDI_APP_ICON 101
#define IDR_PNG_BURNING_DC 201
#define IDR_PNG_SPINNING_DISC 202


#define IDR_BIN_CDIRIP 301
#define IDR_BIN_CDRECORD 302
#define IDR_BIN_CYGWIN 303
#define IDR_BIN_GROWISOFS 304
#define IDR_BIN_DVD_MEDIAINFO 305
#define IDR_WAV_BURN_COMPLETE 501

#define IDR_LICENSE_THIRD_PARTY 401
#define IDR_LICENSE_CDIRIP 402
#define IDR_LICENSE_CDRECORD_CDDL 403
#define IDR_LICENSE_CDRECORD_GPL 404
#define IDR_LICENSE_CYGWIN 405
#define IDR_LICENSE_IMGUI 406
#define IDR_PNG_BURNING_PS1 203
#define IDR_PNG_BURNING_PS2 204
#define IDR_PNG_BURNING_SATURN 205
#define IDR_PNG_BURNING_XBOX360 206
